workflows:
  im_rich_ultra:
    name: I'm Rich Ultra CI
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_BUNDLE_ID: "com.richflex.imrichultra"

    scripts:
      # 1) Récupérer les dépendances
      - name: Get Flutter packages
        script: |
          flutter pub get

      # 2) Build iOS IPA uniquement
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-tree-shake-icons

    artifacts:
      # On garde seulement l’IPA
      - build/ios/ipa/*.ipa
