platform :ios, '13.0'

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_ios_plugin_pods
  target 'RunnerTests' do
    inherit! :search_paths
  end
end
